// React/src/App.tsx
import { useCallback } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import PivotGrid, {
  FieldPanel,
  FieldChooser,
  Export,
} from 'devextreme-react/pivot-grid';
import type { PivotGridTypes } from 'devextreme-react/pivot-grid';
import { exportPivotGrid } from 'devextreme/excel_exporter';
import { Workbook } from 'exceljs';
import { saveAs } from 'file-saver';
import AdventureWorksService from './adventureworks.service';

const dataSource = AdventureWorksService.getPivotGridDataSource();

function App(): JSX.Element {
  const exportGrid = useCallback((e: PivotGridTypes.ExportingEvent) => {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Sales');

    exportPivotGrid({
      component: e.component,
      worksheet,
    }).then(() => workbook.xlsx.writeBuffer().then((buffer) => {
      saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Sales.xlsx');
      return buffer;
    })).catch(() => undefined);
    e.cancel = true;
  }, []);

  return (
    <PivotGrid
      id="pivot-grid"
      dataSource={dataSource}
      allowSorting={true}
      allowSortingBySummary={true}
      allowFiltering={true}
      onExporting={exportGrid}>
      <FieldPanel
        visible={true}
        showFilterFields={false}
      />
      <FieldChooser
        allowSearch={true}
      />
      <Export enabled={true} />
    </PivotGrid>
  );
}

export default App;

// Vue/src/App.vue
<template>
    <DxPivotGrid
        id="pivotGrid"
        :data-source="dataSource"
        :allow-sorting="true"
        :allow-sorting-by-summary="true"
        :allow-filtering="true"
        @exporting="onExporting">
        <DxFieldPanel
            :visible="true"
            :show-filter-fields="false"
        />
        <!-- <DxFieldChooser :enabled="true" /> -->
        <DxExport :enabled="true" />
    </DxPivotGrid>
</template>

<script>
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css'

import {
    DxPivotGrid,
    DxFieldPanel,
    // DxFieldChooser,
    DxExport
} from 'devextreme-vue/pivot-grid';
import AdventureWorksService from './adventureworks.service';
import { exportPivotGrid } from 'devextreme/excel_exporter';
import { Workbook } from 'exceljs';
import saveAs from 'file-saver';

export default {
  name: 'Getting Started with DevExtreme PivotGrid',
  components: {
    DxPivotGrid,
    DxFieldPanel,
    // DxFieldChooser,
    DxExport
  },
  data() {
      return {
          dataSource: AdventureWorksService.getPivotGridDataSource()
      }
  },
  methods: {
      onExporting (e) {
        const workbook = new Workbook();
        const worksheet = workbook.addWorksheet('Sales');
        
        exportPivotGrid({
            component: e.component,
            worksheet: worksheet
        }).then(function() {
            workbook.xlsx.writeBuffer().then(function(buffer) {
                saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Sales.xlsx');
            });
        });
        e.cancel = true;
      }
  }
}
</script>

<style>
#pivotGrid {
    height: 70vh;
}
</style>
