// React/src/App.tsx
import { useCallback } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import PivotGrid, {
  FieldPanel,
  FieldChooser,
  Export,
} from 'devextreme-react/pivot-grid';
import type { PivotGridTypes } from 'devextreme-react/pivot-grid';
import { exportPivotGrid } from 'devextreme/excel_exporter';
import { Workbook } from 'exceljs';
import { saveAs } from 'file-saver';
import AdventureWorksService from './adventureworks.service';

const dataSource = AdventureWorksService.getPivotGridDataSource();

function App(): JSX.Element {
  const exportGrid = useCallback((e: PivotGridTypes.ExportingEvent) => {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Sales');

    exportPivotGrid({
      component: e.component,
      worksheet,
    }).then(() => workbook.xlsx.writeBuffer().then((buffer) => {
      saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Sales.xlsx');
      return buffer;
    })).catch(() => undefined);
    e.cancel = true;
  }, []);

  return (
    <PivotGrid
      id="pivot-grid"
      dataSource={dataSource}
      allowSorting={true}
      allowSortingBySummary={true}
      allowFiltering={true}
      onExporting={exportGrid}>
      <FieldPanel
        visible={true}
        showFilterFields={false}
      />
      <FieldChooser
        allowSearch={true}
      />
      <Export enabled={true} />
    </PivotGrid>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AdventureWorksService, PivotGridDataSource } from './adventureworks.service';
import { exportPivotGrid } from 'devextreme/excel_exporter';
import { Workbook } from 'exceljs';
import saveAs from 'file-saver';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [AdventureWorksService]
})
export class AppComponent {
  title = 'Getting Started with DevExtreme PivotGrid';
  dataSource: PivotGridDataSource;
  constructor(service: AdventureWorksService) {
    this.dataSource = service.getPivotGridDataSource();
  }
  onExporting (e) {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Sales');
    
    exportPivotGrid({
        component: e.component,
        worksheet: worksheet
    }).then(function() {
        workbook.xlsx.writeBuffer().then(function(buffer) {
            saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Sales.xlsx');
        });
    });
    e.cancel = true;
  }
}

<dx-pivot-grid
    id="pivot-grid"
    [dataSource]="dataSource"
    [allowSorting]="true"
    [allowSortingBySummary]="true"
    [allowFiltering]="true"
    (onExporting)="onExporting($event)">
    <dxo-field-panel
        [visible]="true"
        [showFilterFields]="false">
    </dxo-field-panel>
    <!-- <dxo-field-chooser
        [enabled]="true">
    </dxo-field-chooser> -->
    <dxo-export
        [enabled]="true">
    </dxo-export>
</dx-pivot-grid>
